image: jamesdbloom/docker-java8-maven:latest

stages:
  - deploy

deployment:
  stage: deploy
  script:
    - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-218.0.0-linux-x86.tar.gz
    - tar -xzf  google-cloud-sdk-218.0.0-linux-x86.tar.gz
    - ./google-cloud-sdk/install.sh
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - ls $CI_PROJECT_DIR
    - source $CI_PROJECT_DIR/google-cloud-sdk/path.bash.inc
    - ./google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
    #- mvn appengine:deploy -Pcloud
