image: jamesdbloom/docker-java8-maven:latest

stages:
  - compile
  - unit_test
  - integration_test
  - deploy

build:
  stage: compile
  script:
    - mvn clean compile
  only:
    - merge_requests
    - master
    
unit_test:
  stage: unit_test
  script:
    - mvn clean test
  only:
    - merge_requests
    - master
    
integration_test:
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: roboadvisor
    MYSQL_ROOT_PASSWORD: roboadvisor
  stage: integration_test
  script: 
    - mvn clean -DskipSurefire integration-test -Ptest
  only:
    - merge_requests
    - master

production:
  stage: deploy
  script:
    - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-218.0.0-linux-x86.tar.gz
    - tar -xzf  google-cloud-sdk-218.0.0-linux-x86.tar.gz
    - ./google-cloud-sdk/install.sh
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - source /builds/cpsc319-2018w2/hsbc/formation/roboadvisor-api/google-cloud-sdk/path.bash.inc
    - ./google-cloud-sdk/bin/gcloud config set project hsbc-roboadvisor
    - mvn appengine:deploy -Pcloud
  only:
    - master
