runtime: java
env: flex
service: fund-rebalancer
runtime_config:
   jdk: openjdk8
resources:
  memory_gb: 2
manual_scaling:
  instances: 1
handlers:
  - url: /.*
    script: this field is required, but ignored
